### PR TITLE
Replace logging in submit call with returning of error

### PR DESCRIPTION
**Pull request by ajmath**
We have an application using the AWS Kinesis multi lang daemon.  An assumption of this tool is that it can communicate freely over stdin/stdout with it's sub processes (our go app).  When raygun4go outputs confirmations and errors related to sending of errors to raygun to stdout, it breaks the Kinesis multi-lang daemon.  This PR changes outputting to stdout to only happen when in silent mode.  In all other cases, errors are returned and lack of an error indicates a success.

### CODE REVIEW

**Comment by JaycobA** [comment]
Hi ajmath, thanks for your contribution.

This definitely makes sense, we don't want to force users to pollute their stdout. However, if I read your code correctly, you are handing down the error to HandleError(), which then returns the error. But as HandleError() is called as a deferred function, there is no-one to process the returned error. So we would essentially lose any knowledge of the error. 

Could you please add an option (e.g. PrintErrorsToStdOut) that prints the error in HandleError()?. This way we could still give people the opportunity to have the error printed, without polluting everyones output.

**Comment by ajmath** [comment]
Thanks for the comment.  I definitely agree that adding a flag is the right way to go.  It wasn't needed for my immediate use case though so I punted it.  When I get the chance I'll modify and let you know.

**Comment by ajmath** [comment]
I updated the PR adding an option to log to std out.  When this is enabled, both failures in sending the message and confirmations that the message was sent are logged to std out.

It can be enabled by calling `client.LogToStdOut(true)`

**Comment by crahles** [comment]
Hi ajmath,

Looks good - thank you!

**Pull request merged**
