### PR TITLE
Expose submit method

### PR DESCRIPTION
**Pull request by douglas-soares**
With this change it's possible to send custom stacktrace for the Raygun service.

### CODE REVIEW

**Comment by QuantumNightmare** [comment]
Thanks for this PR + formatting clean up.
Looks good :+1:

**Comment by QuantumNightmare** [comment]
@douglas-soares Before I merge this, could you please update the version number in version.go to 1.1.0

**Comment by douglas-soares** [comment]
Hey Quantum! I've updated the version.

**Comment by QuantumNightmare** [comment]
Thanks!, merging this now

**Pull request merged**
